// dsgn theme 0.11.0 — generated by build/plugin.mjs, do not edit.

async function dsgnApplyTheme(P) {
  const hex = (h) => ({ r: parseInt(h.slice(1, 3), 16) / 255, g: parseInt(h.slice(3, 5), 16) / 255, b: parseInt(h.slice(5, 7), 16) / 255, a: h.length > 7 ? parseInt(h.slice(7, 9), 16) / 255 : 1 });
  const cols = await figma.variables.getLocalVariableCollectionsAsync();
  const vars = await figma.variables.getLocalVariablesAsync();
  const done = [];
  for (const [colName, values, conv] of [['Primitives', P.primitives, hex], ['Typography', P.typography, (x) => x]]) {
    if (!Object.keys(values).length) continue;
    const col = cols.find((c) => c.name === colName);
    if (!col) throw new Error('This file has no "' + colName + '" variables. Run it in the dsgn library file.');
    if (colName === 'Typography') {   // a font family can only be set when the font is available in Figma
      try { await figma.loadFontAsync({ family: values['family/sans'], style: 'Regular' }); }
      catch (e) { done.push('Font "' + values['family/sans'] + '" is not available in Figma, so the font was not changed.'); continue; }
    }
    const mode = col.modes.find((m) => m.name === P.mode);
    const modeId = mode ? mode.modeId : col.addMode(P.mode);   // Figma limits modes per collection by plan (Professional 10)
    let n = 0;
    for (const [name, val] of Object.entries(values)) {
      const v = vars.find((x) => x.variableCollectionId === col.id && x.name === name);
      if (!v) throw new Error('Variable not found: ' + colName + ' / ' + name);
      v.setValueForMode(modeId, conv(val)); n++;
    }
    done.push(colName + ': ' + (mode ? 'updated' : 'added') + ' mode "' + P.mode + '" (' + n + ' values)');
  }
  if (P.roles) done.push(await dsgnSetRoles(P.roles, cols, vars));
  return done;
}
// Role slots live in the Accent collection as aliases to Primitives palette steps. Its Default mode is the
// file's choice (one per file); a theme with accentFill or monochrome re-points it, removing a theme restores it.
async function dsgnSetRoles(roles, cols, vars) {
  cols = cols || await figma.variables.getLocalVariableCollectionsAsync();
  vars = vars || await figma.variables.getLocalVariablesAsync();
  const acc = cols.find((c) => c.name === 'Accent'), prim = cols.find((c) => c.name === 'Primitives');
  if (!acc || !prim) return 'Accent: no Accent collection, role slots not changed';
  const def = acc.modes[0].modeId;
  let n = 0, changed = 0;
  for (const [name, target] of Object.entries(roles)) {
    const v = vars.find((x) => x.variableCollectionId === acc.id && x.name === name);
    const p = vars.find((x) => x.variableCollectionId === prim.id && x.name === target);
    if (!v || !p) continue;
    const cur = v.valuesByMode[def];
    if (!(cur && cur.type === 'VARIABLE_ALIAS' && cur.id === p.id)) changed++;
    v.setValueForMode(def, figma.variables.createVariableAlias(p)); n++;
  }
  return 'Accent: Default mode role slots ' + (changed ? 're-pointed (' + changed + ' of ' + n + ')' : 'unchanged (' + n + ')');
}
const DSGN_DEFAULT_ROLES = {"accent/fill-light":"color/accent/54","accent/fill-hover-light":"color/accent/46","accent/fill-pressed-light":"color/accent/38","control/fill-light":"color/accent/54","control/fill-hover-light":"color/accent/46","control/fill-pressed-light":"color/accent/38","control/tint-light":"color/accent/94","control/tint-hover-light":"color/accent/90","control/tint-pressed-light":"color/accent/85","control/text-light":"color/accent/38","control/focus-light":"color/accent/54","accent/fill-dark":"color/accent/64","accent/fill-hover-dark":"color/accent/70","accent/fill-pressed-dark":"color/accent/76","control/fill-dark":"color/accent/64","control/fill-hover-dark":"color/accent/70","control/fill-pressed-dark":"color/accent/76","control/tint-dark":"color/accent/26","control/tint-hover-dark":"color/accent/30","control/tint-pressed-dark":"color/accent/38","control/text-dark":"color/accent/85","control/focus-dark":"color/accent/70"};
async function dsgnRemoveTheme(name) {
  const cols = await figma.variables.getLocalVariableCollectionsAsync();
  const done = [];
  for (const colName of ['Primitives', 'Typography']) {
    const col = cols.find((c) => c.name === colName); if (!col) continue;
    const i = col.modes.findIndex((m) => m.name === name);
    if (i > 0) { col.removeMode(col.modes[i].modeId); done.push(colName + ': removed mode "' + name + '"'); }   // never the first (package) mode
  }
  if (done.length) done.push(await dsgnSetRoles(DSGN_DEFAULT_ROLES));
  return done;
}
async function dsgnStatus() {
  const cols = await figma.variables.getLocalVariableCollectionsAsync();
  const prim = cols.find((c) => c.name === 'Primitives');
  if (!prim) return { library: false };
  const saved = {};
  for (const m of prim.modes.slice(1)) saved[m.name] = prim.getSharedPluginData('dsgn', 'theme:' + m.name) || '';
  return { library: true, themes: prim.modes.slice(1).map((m) => m.name), saved, file: figma.root.name };
}
figma.showUI(__html__, { width: 380, height: 680, themeColors: true });
figma.ui.onmessage = async (msg) => {
  try {
    if (msg.type === 'status') {
      figma.ui.postMessage({ type: 'status', status: await dsgnStatus() });
      const fonts = await figma.listAvailableFontsAsync();
      figma.ui.postMessage({ type: 'fonts', families: [...new Set(fonts.map((f) => f.fontName.family))].sort() });
    } else if (msg.type === 'apply') {
      const done = await dsgnApplyTheme(msg.payload);
      const cols = await figma.variables.getLocalVariableCollectionsAsync();
      const prim = cols.find((c) => c.name === 'Primitives');
      if (prim && msg.code) prim.setSharedPluginData('dsgn', 'theme:' + msg.payload.mode, msg.code);
      figma.ui.postMessage({ type: 'done', done, status: await dsgnStatus() });
    } else if (msg.type === 'remove') {
      const cols = await figma.variables.getLocalVariableCollectionsAsync();
      const prim = cols.find((c) => c.name === 'Primitives');
      if (prim) prim.setSharedPluginData('dsgn', 'theme:' + msg.name, '');
      const done = await dsgnRemoveTheme(msg.name);
      figma.ui.postMessage({ type: 'done', done, status: await dsgnStatus() });
    } else if (msg.type === 'close') figma.closePlugin();
  } catch (e) {
    figma.ui.postMessage({ type: 'error', message: String(e && e.message || e) });
  }
};
