// dsgn theme 0.10.0 — generated by build/plugin.mjs, do not edit.

async function dsgnApplyTheme(P) {
  const hex = (h) => ({ r: parseInt(h.slice(1, 3), 16) / 255, g: parseInt(h.slice(3, 5), 16) / 255, b: parseInt(h.slice(5, 7), 16) / 255 });
  const cols = await figma.variables.getLocalVariableCollectionsAsync();
  const vars = await figma.variables.getLocalVariablesAsync();
  const done = [];
  for (const [colName, values, conv] of [['Primitives', P.primitives, hex], ['Typography', P.typography, (x) => x]]) {
    if (!Object.keys(values).length) continue;
    const col = cols.find((c) => c.name === colName);
    if (!col) throw new Error('This file has no "' + colName + '" variables. Run it in the dsgn library file.');
    if (colName === 'Typography') {   // a font family can only be set when the font is available in Figma
      try { await figma.loadFontAsync({ family: values['family/sans'], style: 'Regular' }); }
      catch (e) { done.push('Font "' + values['family/sans'] + '" is not available in Figma, so the font was not changed.'); continue; }
    }
    const mode = col.modes.find((m) => m.name === P.mode);
    const modeId = mode ? mode.modeId : col.addMode(P.mode);   // Figma limits modes per collection by plan (Professional 10)
    let n = 0;
    for (const [name, val] of Object.entries(values)) {
      const v = vars.find((x) => x.variableCollectionId === col.id && x.name === name);
      if (!v) throw new Error('Variable not found: ' + colName + ' / ' + name);
      v.setValueForMode(modeId, conv(val)); n++;
    }
    done.push(colName + ': ' + (mode ? 'updated' : 'added') + ' mode "' + P.mode + '" (' + n + ' values)');
  }
  return done;
}
async function dsgnRemoveTheme(name) {
  const cols = await figma.variables.getLocalVariableCollectionsAsync();
  const done = [];
  for (const colName of ['Primitives', 'Typography']) {
    const col = cols.find((c) => c.name === colName); if (!col) continue;
    const i = col.modes.findIndex((m) => m.name === name);
    if (i > 0) { col.removeMode(col.modes[i].modeId); done.push(colName + ': removed mode "' + name + '"'); }   // never the first (package) mode
  }
  return done;
}
async function dsgnStatus() {
  const cols = await figma.variables.getLocalVariableCollectionsAsync();
  const prim = cols.find((c) => c.name === 'Primitives');
  if (!prim) return { library: false };
  const saved = {};
  for (const m of prim.modes.slice(1)) saved[m.name] = prim.getSharedPluginData('dsgn', 'theme:' + m.name) || '';
  return { library: true, themes: prim.modes.slice(1).map((m) => m.name), saved, file: figma.root.name };
}
figma.showUI(__html__, { width: 380, height: 680, themeColors: true });
figma.ui.onmessage = async (msg) => {
  try {
    if (msg.type === 'status') {
      figma.ui.postMessage({ type: 'status', status: await dsgnStatus() });
      const fonts = await figma.listAvailableFontsAsync();
      figma.ui.postMessage({ type: 'fonts', families: [...new Set(fonts.map((f) => f.fontName.family))].sort() });
    } else if (msg.type === 'apply') {
      const done = await dsgnApplyTheme(msg.payload);
      const cols = await figma.variables.getLocalVariableCollectionsAsync();
      const prim = cols.find((c) => c.name === 'Primitives');
      if (prim && msg.code) prim.setSharedPluginData('dsgn', 'theme:' + msg.payload.mode, msg.code);
      figma.ui.postMessage({ type: 'done', done, status: await dsgnStatus() });
    } else if (msg.type === 'remove') {
      const cols = await figma.variables.getLocalVariableCollectionsAsync();
      const prim = cols.find((c) => c.name === 'Primitives');
      if (prim) prim.setSharedPluginData('dsgn', 'theme:' + msg.name, '');
      const done = await dsgnRemoveTheme(msg.name);
      figma.ui.postMessage({ type: 'done', done, status: await dsgnStatus() });
    } else if (msg.type === 'close') figma.closePlugin();
  } catch (e) {
    figma.ui.postMessage({ type: 'error', message: String(e && e.message || e) });
  }
};
